# Generated by Django 3.2.16 on 2023-01-29 12:36

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=django_jsonform.models.fields.JSONField(),
        ),
    ]
